### ISSUE TITLE
ERRORS WITH ITEMS

### ISSUE THREAD

**Issue by ToastieYum** [xionbig/SignShop#12]
I know how to make my sign shop but now i have updated to 0.13.1 or the server is updated or some think i cant make any sign shops all the items have errors can you fixs this my server needs it THX
Btw i make my SignShops like this
/signbuy
ITEM
AmountXcost
9999

**Comment by NikoZazza** [comment]
the plugin reports the error when creating the sign?

**Comment by toastedsandwhich** [comment]
hai and yes once i made the sign and exited the sign it came with error for all items in the game if thats what you mean

**Comment by toastedsandwhich** [comment]
Btw my freinds are haveing the same trubble on there servers to and the errors are on the

**Comment by toastedsandwhich** [comment]
hai and yes once i made the sign and exited the sign it came with error for all items in the game if thats what you mean

Btw my freinds are haveing the same trubble on there servers to and the errors are on there servers to

**Comment by ToastieYum** [comment]
hai and yes once i made the sign and exited the sign it came with error for all items in the game if thats what you mean

Btw my freinds are haveing the same trubble on there servers to and the errors are on there servers to

I have used sign shop befor and i had no issues
