### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by wizardtamere** [xionbig/SignShop#18]
hi I have a problem, I put the plugin crash my server

**Comment by NikoZazza** [comment]
#17 The current version does not support pocketmine and its derivatives that use PHP7. you can get the right version for your server here https://mega.nz/#!MBcBQJAa!34LnF1i5_6zhY9K71VPONXYJH0hTahqN34GT4eD10qw

**Comment by wizardtamere** [comment]
Even with your version it still does not work
