### ISSUE TITLE
Shuts down server on crash

### ISSUE THREAD

**Issue by inxomnyaa** [xionbig/SignShop#24]
I was wondering why PMMP keeps crashing. Reason: the plugin still requests $sign after it says 'depends on bla and needs it'
![image_2016-12-20_11-42-46](https://cloud.githubusercontent.com/assets/8733998/21347760/4f8af2fc-c6aa-11e6-9397-348ef3618573.png)

**Comment by inxomnyaa** [comment]
-.- https://github.com/NikoZazza/SignShop/blob/master/src/SignShop/Manager/MoneyManager.php#L50-L53

Do NOT shut down the server! Use disablePlugin!!! Oh man

**Comment by NikoZazza** [comment]
You must install one of the following plugins: -EconomyS -PocketMoney -MassiveEconomy

**Comment by inxomnyaa** [comment]
Yes, they simply crashed due to an API update.
Still, you don't shut down the server when a plugin fails.

**Comment by dktapps** [comment]
What's wrong with the plugin simply disabling itself instead of shutting down the entire server?

**Comment by NikoZazza** [comment]
I don't know, but I will change the code ..

**Comment by inxomnyaa** [comment]
Thanks

**Comment by NyaomiDEV** [comment]
Nikola our savior will fix them all~~~~~~~~~~~ ^.^

**Comment by NikoZazza** [comment]
fixed on https://github.com/NikoZazza/SignShop/commit/d65913d332dc8692825a1af4525641990d18a30f

**Comment by inxomnyaa** [comment]
Neat

**Comment by inxomnyaa** [comment]
Wait what? That commit has nothing to do with the shutdown function

**Comment by dktapps** [comment]
https://imgur.com/lfL0UvH
