### ISSUE TITLE
Signshop color

### ISSUE THREAD

**Issue by SinlesFlyer376** [xionbig/SignShop#25]
Should have it to where the sign message changes colors each second

**Comment by NikoZazza** [comment]
The color will be chosen by you or the color will not be customizable?

**Comment by SinlesFlyer376** [comment]
No I mean it should change color automatically

**Comment by SinlesFlyer376** [comment]
The the top line is AQUA then it turns into like LIGHT_AQUA

**Comment by SinlesFlyer376** [comment]
Automatically every 1 second

**Comment by SinlesFlyer376** [comment]
LIGHt_BLUE *

**Comment by SinlesFlyer376** [comment]
So if you could that would be awesome

**Comment by SinlesFlyer376** [comment]
@Sinles_Flyer376 is my twitter

**Comment by SinlesFlyer376** [comment]
Ik this has nothing to do with Sign shop so you can close this but, How can I implement my Custom Enchants plugin onto my server? The plugin doesn't work and i keep getting msged to update the phar for the enchants. I have no idea how to do so

**Comment by SinlesFlyer376** [comment]
?

**Comment by NikoZazza** [comment]
I'll add this feature, but for now the priority is fix the bugs. Regarding the plugin of the Enchants I do not know and then I can not help you. If you link to me the plugin maybe I could help you

**Comment by SinlesFlyer376** [comment]
There is no link but if you have an email I can send it to you from there

**Comment by SinlesFlyer376** [comment]
Also dm me on twitter and close this please @Sinles_Flyer376
