### ISSUE TITLE
Server stops after normal start EconomyS+SignShop

### ISSUE THREAD

**Issue by vvzar** [xionbig/SignShop#3]
It happens both, with Yaml and MySQL providers. While no visible errors appear. If database is absent (not created) I see in console error Can`t access to the database. If I create it manually -server stops again after successful start

**Comment by vvzar** [comment]
Versions I tried: 1.1.0 and 1.1.1
EconomyAPI 2.0.8

**Comment by NikoZazza** [comment]
Can you send some screen? It does not make any mistake

**Comment by vvzar** [comment]
Yes, it does not show any errors. 
Server started in 2.86 seconds.
Server starting finished
Disabled EconomyAPI
Disabled Pureperms 
...
...
Kicked player. Reason: server closed.
And so on
$~/server-mpe

**Comment by vvzar** [comment]
it is not exactly what wrote in log but shows what happens with server

**Comment by NikoZazza** [comment]
Are you sure that this problem is caused by SignShop?

**Comment by NikoZazza** [comment]
you can send me the log or anything that we can help solve the problem?

**Comment by vvzar** [comment]
I can only prove that if I remove signshop - server not stopped just after finished starting.
I have build 1258 and I can remove my 8 plugins and keep only economyapi and signshop

**Comment by vvzar** [comment]
[01:32:37] [Server thread/INFO]: Включение SignShop v1.1.1
[01:32:37] [Server thread/CRITICAL]: [SignShop] The version of EconomyS
is too old! Please update EconomyS to version 5.5
[01:32:37] [Server thread/INFO]: SignShop v1.1.1 Enabled!
[01:32:37] [Server thread/INFO]: Включение EconomyAPI v2.0.8
[01:32:37] [Server thread/NOTICE]: [EconomyAPI] Auto save has been set t
o interval : 10 min(s)

**Comment by vvzar** [comment]
I found that the economyapi is too new? Old

**Comment by NikoZazza** [comment]
This is a mistake that I did, thank you very much for reporting

**Comment by NikoZazza** [comment]
I updated the plugin, try the new version and tell me if it works
https://github.com/xionbig/SignShop/blob/master/SignShop_v1.1.2.phar
